services:
  flask_gallery:
    build: .
    container_name: flask_gallery
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask_gallery.rule=Host(`gallery.jat.localhost`)"
      - "traefik.http.routers.flask_gallery.tls=true"
      - "traefik.http.routers.flask_gallery.entrypoints=websecure"
    environment:
      SECRET_KEY: "thisisasecretkey"
      SQLALCHEMY_DATABASE_URI: "mariadb+mariadbconnector://user:password@flask_gallery_db:3306/mydb"
      SITE_NAME: "Flask Gallery"
    depends_on:
      - flask_gallery_db
    networks:
      - proxy

  flask_gallery_db:
    image: mariadb:latest
    container_name: flask_gallery_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - proxy

volumes:
    mysql-data:

networks:
  proxy:
    external: true