#file: noinspection UndefinedAction
name: Flake8

on: [ push ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: install MariaDB client library
        run: sudo apt install libmariadb3 libmariadb-dev

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          # noinspection UndefinedParamsPresent
          python-version: '3.12'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8 app/