#file: noinspection UndefinedAction
name: flake8
on: [ push ]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # noinspection UndefinedParamsPresent
          python-version: '3.12'
      - run: pip install -r requirements.txt  # install requirements to enable GitHub run tests
      - run: flake8 app/  # run pylint on the app directory